# Generated by Django 4.0.3 on 2022-05-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_color_remove_order_size_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Delivered', 'delivered'), ('Dispatch', 'dispatch')], default='Pending', max_length=100),
        ),
    ]
